# Generated by Django 6.0.1 on 2026-01-29 12:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='uploads/')),
                ('result_mask', models.ImageField(upload_to='results/')),
                ('area_m2', models.FloatField(help_text='Площадь застройки в квадратных метрах')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Результат сегментации',
                'verbose_name_plural': 'Результаты сегментации',
                'ordering': ['-created_at'],
            },
        ),
    ]
